version: 1.2.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_folder: c:\projects\godsharp.serialport
install:
- cmd: nuget restore
nuget:
  account_feed: true
  project_feed: true
build:
  project: GodSharp.SerialPort.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
test: off
artifacts:
- path: test\GodSharp.SerialPort.ConsoleSample\bin\$(configuration)\
  name: GodSharp.SerialPort.ConsoleSample-v$(appveyor_build_version)
deploy:
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: s388/c8yQWnGyZ9v9cUDfBe4ud6MFl/ouUEEBruiN5j5+LjSQ4giGKMKuLuvglS1
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  server: https://www.myget.org/F/seay/api/v2/package
  api_key:
    secure: CKm5m2qGYNYnh5yDUE2zKfN+JKBmO5xmtG80AP0yni9yPBqDOaRQ48Y/4k8KGo2y
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
- provider: GitHub
  description: Release.
  auth_token:
    secure: uCHTzET52dtiexqTKhgQmup+EBGZs1Afw6eBMfvN4PbQ720YaybNd890Y96ISZ0T
  artifact: /.*\.(?:nupkg|zip)/
  draft: true
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true